Default: &defaults
  host: "*4" # any IPv4 host
  port: 3000
  approot: "http://192.168.10.150:3000"
  password: pass

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  <<: *defaults
