Default: &defaults
  host: "*4" # any IPv4 host
  port: 3000
  approot: "http://192.168.10.200:3000"
  email: raphaeljavaux@gmail.com
  password: pass

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  <<: *defaults
