Default: &defaults
  host: "*4" # any IPv4 host
  port: 3000
  approot: "http://127.0.0.1:3000"
  password: pass

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  <<: *defaults
