Default: &defaults
  database: bechouette.sqlite3
  poolsize: 1

Development:
  <<: *defaults

Testing:
  database: bechouette_test.sqlite3
  <<: *defaults

Staging:
  database: bechouette_staging.sqlite3
  poolsize: 1
  <<: *defaults

Production:
  database: bechouette_production.sqlite3
  poolsize: 1
  <<: *defaults
